[package]
name = "parser"
version = "0.1.0"
edition = "2021"

[dependencies]
phf = { version = "0.10", features = ["macros"] }
calamine = "0.22"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
xlsxwriter = "0.6.1"
